#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <Arduino.h>

// --- PIOUT ---
#define RGB_R_PIN 11
#define RGB_G_PIN 10
#define RGB_B_PIN 9

#define BUTTON_UP 2
#define BUTTON_DOWN 3
#define BUTTON_RIGHT 5
#define BUTTON_LEFT 4

#define LCD_BACKLIGHT_PIN 6
#define LDR_PIN A7

// --- SOFTWARE VERSIONS ---
#define SOFTWARE_MAJOR_VERSION 1
#define SOFTWARE_MINOR_VERSION 4
#define SOFTWARE_PATCH_VERSION 4

#define MINIMUM_SOFTWARE_MAJOR_VERSION 1
#define MINIMUM_SOFTWARE_MINOR_VERSION 4
#define MINIMUM_SOFTWARE_PATCH_VERSION 0

// --- ERROR CODES ---
#define FIRMWARE_VERSION_ERROR_CODE 11
#define VERSION_NOT_SUPPORTED_CODE 12
#define DOWNGRADED_FIRMWARE_CODE 13
#define PROGRAM_LOOP_FAILURE_CODE 14
#define RAM_FAILURE_CODE 15

#endif